Tags blogpost
technologiestiftung/lab-site pull request #320
Opened 2021-03-12 14:12 UTC by Lisa-Stubert

WIP

2021-03-15 09:45 UTC, ff6347 requested changes

2021-03-15 09:45 UTC, ff6347 commented on source/projects/tag-analysis/de/index.md
> +lang: de
If this is the english version the set `lang: en`

2021-03-15 09:45 UTC, ff6347 commented on source/projects/tag-analysis/de/index.md
> +- **[Try it yourself here!]()**
Missing link

2021-03-15 09:45 UTC, ff6347 commented on source/projects/tag-analysis/en/index.md
> +lang: en
Also `en`?

2021-03-15 09:45 UTC, ff6347 commented on source/projects/tag-analysis/en/index.md
> +- **[Try it yourself here!]()**
missing link

2021-03-15 09:50 UTC, ff6347 commented
The diagram looks pretty huge.

2021-03-16 12:13 UTC, Lisa-Stubert commented
needs final content review. pls do not merge

2021-03-16 12:15 UTC, ff6347 commented
> needs final content review. pls do not merge

Maybe we set it to draft state.

2021-03-19 13:58 UTC, Lisa-Stubert commented on source/projects/tag-analysis/en/index.md
> +lang: en
en content was added now

2021-03-19 14:17 UTC, Lisa-Stubert commented on source/projects/tag-analysis/en/index.md
> +- **[Try it yourself here!]()**
link is working now

2021-03-19 14:17 UTC, Lisa-Stubert commented on source/projects/tag-analysis/de/index.md
> +- **[Try it yourself here!]()**
link is working now

2021-03-19 14:18 UTC, Lisa-Stubert commented
@ff6347 @dnsos this pull request is ready for merge now

2021-03-22 15:09 UTC, ff6347 approved these changes
LGTM

2021-03-22 17:22 UTC, dnsos approved these changes
Merging this now.

2021-03-22 17:22 UTC, merged